[tool.poetry]
name = "pydantic-media-type"
version = "0.1.0"
description = "Pydantic model for MIME/Media types"
authors = ["Youri Westerman <y.westerman@amsterdam.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
