[tool.poetry]
name = "pydantic-media-type"
version = "0.1.0"
description = "Pydantic model for MIME/Media types"
authors = ["Youri Westerman <y.westerman@amsterdam.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.1"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
isort = "^5.13.2"
mypy = "^1.12.1"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
overwrite_in_place = true

[tool.mypy]
strict = true
