name: Cleanup Packages
on:
  workflow_dispatch: ~
  schedule:
    - cron: '15 8 * * *'
permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'pydantic-media-type'
          package-type: 'container'
          min-versions-to-keep: 2
